<a href="https://colab.research.google.com/github/seojeong17/bioinfomatics/blob/main/______Numpy____1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


1. **Numpy**

2. **np.array()**

  1) ndarray의 데이터 타입

  2) ndarray를 편리하게 생성하기

3.  **차원과 크기 변경: reshape()**

4.  **데이터 세트 선택하기 - 인덱싱(Indexing)**

5. **행렬의 정렬 - sort()와 argsort()**

6. **선형대수 연산 - 행렬 내적과 전치 행렬 구하기**

7. **배열 간 사칙연산**

8. **Broadcasting**

9. **집계(Aggregation)**

  1) 합계

  2) 평균

  3) 곱셈

  4) 최댓값과 최솟값

  5) 표준편차와 분산


<div><span>



---



## **1. Numpy**

선형대수는 머신러닝 주요 알고리즘 중 하나입니다.
<br/>넘파이는 파이썬에서 선형대수 기반 프로그램을 가능하게 하는 대표적인 패키지이며 빠른 계산과 배열 연산 능력을 보장합니다.

수행 성능이 중요시될 때는 C/C++ 기반의 코드를 넘파이에서 호출하여 쉽게 통합할 수도 있습니다.
<br/> 딥러닝 프레임워크인 텐서플로가 앞서 말한 방식으로 작성됐습니다.

넘파이는 다양한 데이터 핸들링 기능도 제공하지만 데이터 처리 패키지인 판다스의 편리성은 따라가지 못합니다.
<br/> 그러나 많은 머신러닝 알고리즘이 넘파이를 기반으로 하기 때문에 넘파이에 익숙해지는 것이 매우 중요합니다.

ㅤ

In [ ]:
import numpy as np

ㅤ

In [ ]:
data = [1,2,3,4]
result = []

for i in data :
  result.append(i*10)

print(result, type(result))

[10, 20, 30, 40] <class 'list'>


In [ ]:
#넘파이를 이용해 10씩 곱하기
arr = np.array(data)

arr10  = arr*10
print(arr10, type(arr10))

[10 20 30 40] <class 'numpy.ndarray'>


## **2. np.array()**

*   리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능을 수행합니다.
*   .shape로 배열의 모양을 확인할 수 있으며 ndarray의 행과 열의 수를 튜플 형태로 가집니다.
*   대괄호[] 중첩으로 배열이 증가합니다.






In [ ]:
#1차원 배열
배열1 = np.array([1,2,3])
print(배열1)
print(배열1.shape)

[1 2 3]
(3,)


In [ ]:
#2차원 배열
배열2 = np.array([[1,2,3], [4,5,6]])
print(배열2)
print(배열2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
#3차원 배열
배열3 = np.array([[[1,2,3], [4,5,6],[7,8,9]]])
print(배열3)
print(배열3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)


ㅤ

ㅤ

### **1) ndarray의 데이터 타입**






숫자값, 문자열 값, bool 값 등이 모두 가능합니다.

연산의 특성상 같은 데이터 타입만 가능합니다. 즉, 한 개의 ndarray 객체에 int와 float가 함께 있을 수 없습니다.

dtype으로 데이터 타입 속성을 확인 할 수 있습니다.

ㅤ

In [ ]:
list1 = [1.5, 2.4,3.7]
print(type(list1))

array1 = np.array(list1)
print(type(array1))

print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1.5 2.4 3.7] float64


In [ ]:
list2 = [1, 2, 't']
arr2 = np.array(list2)
print(arr2, arr2.dtype)

['1' '2' 't'] <U21


In [ ]:
list2 = [1, 2, 3.5, 4]
arr2 = np.array(list2)
print(arr2, arr2.dtype)

[1.  2.  3.5 4. ] float64


* 서로 다른 데이터 타입이 섞여 있을 경우 데이터 타입이 더 큰 데이터 타입으로 변환됩니다.
* 사용하는 아키텍처에 따라 지정되기 때문에
int64비트가 기본으로 설정


> int형: 8bit, 16bit, 32bit


> unsigned int형: 8bit, 16bit, 32bit


> float형: 16bit, 32bit, 64bit, 128bit











ㅤ

* int8 ( -128 ~ 127 )
* int16 ( -32768 ~ 32767 )
* int32 ( -2147483648 ~ 2147483647 )

메모리를 절약해야 할 때 astype()을 사용하여 ndarray 내 데이터값의 타입을 변경할 수 있습니다.

ㅤ

### **2) ndarray를 편리하게 생성하기**


**[ arange() ]**

arange()는 표준 함수 range()와 유사,
데이터 타입 지정하지 않으면 넘파이가 가장 적절한 타입으로 지정.
~~~
np.arange( 시작번호, 끝번호(포함X), 간격, dtype=데이터타입 )
~~~

In [ ]:
seq_arr = np.arange(10)
print(seq_arr)

[0 1 2 3 4 5 6 7 8 9]


0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환합니다.

**[ linspace() ]**

범위를 정해주고 정해진 수만큼 분할된 수열 생성

~~~
np.linspace( 시작번호, 끝번호(포함), 나눌갯수, dtype=데이터타입 )
~~~
기본 값 실수, arange와 다른점을 끝번호를 포함하여 생성

In [ ]:
seq_arr = np.linspace(1,100, 5, dtype=np.int32)
print(seq_arr, seq_arr.dtype)

[  1  25  50  75 100] int32


ㅤ

**[ zeros() ]**

zeros()는 모든 값을 0으로 채운 배열을 만듭니다.

In [ ]:
zeros = np.zeros(10, dtype=np.int8)
print(zeros, zeros.dtype)

[0 0 0 0 0 0 0 0 0 0] int8


In [ ]:
zeros1 = np.zeros((3,2))
print(zeros1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
zeros2 = np.zeros([3,2])
print(zeros2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


ㅤ

**[ ones() ]**

ones()는 모든 값을 1로 채운 배열을 만듭니다.

In [ ]:
one1 = np.ones((3,2))
print(one1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


ㅤ

**[ random.randn() ]**

random.randn()는 랜덤한 숫자 배열을 만듭니다.

In [ ]:
rd = np.random.randn(3,2)
print(rd)

[[ 2.11953232  0.55015813]
 [-0.74682058 -0.99314932]
 [-0.93531894  0.23948829]]


ㅤ

## **3. 차원과 크기 변경: reshape()**

ndarray를 특정 차원 및 크기로 변환합니다.

지정된 사이즈로 변경이 불가능하면 오류가 발생합니다.

####배열의 차원 확인(뒤에 괄호 붙이지 않음)

~~~
배열이름.ndim
~~~

In [ ]:
a1 =  np.array([1,2,3,4,5])
a2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
a3 = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3,]],[[1,2,3],[1,2,3]]])
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


####배열의 크기
~~~
배열이름.shape
~~~

In [ ]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(5,)
(2, 5)
(3, 2, 3)


####배열의 차원 바꾸기
~~~
배열이름.reshape(행, 열)
~~~

In [ ]:
arr1 = np.arange(10)
print(arr1)

arr2 = arr1. reshape(2,5)
print(arr2)

#arr3 = arr1. reshape(3,3)
#print(arr3)

ㅤ

* 행이나 열중 하나의 갯수만 정하고 나머지는 정하기 힘들때
행,열 자리에 -1 입력,
* reshape(-1, 1)을 이용해 3차원을 2차원으로 2차원을 1차원으로 변경할 수 있습니다.

####행과 열을 바꾸기
~~~
배열이름.T
~~~

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1 = arr.T
arr1

array([[1, 4],
       [2, 5],
       [3, 6]])

####배열  연결하기
* 같은 행인 배열 연결하기
~~~
np.hstack([배열1, 배열2])
~~~

* 같은 열인 배열 연결하기
~~~
np.vstack([배열1, 배열2])
~~~

ㅤ

## **4. 데이터 세트 선택하기: 인덱싱(Indexing)**

### **1) 단일 값 추출**

객체에 해당하는 위치의 인덱스 값을 [ ]안에 입력합니다.

In [ ]:
arr = np.arange(1,10)
print(arr)
print(arr[2])
print(arr[-1])

[1 2 3 4 5 6 7 8 9]
3
9


ㅤ

단일 인덱스를 이용해 데이터값 수정도 가능합니다.

In [ ]:
arr[0] = 10
print(arr)

[10  2  3  4  5  6  7  8  9]


ㅤ

다차원에서 단일 값을 추출할 수 있습니다.

In [ ]:
arr2 = arr.reshape(3,3)
print(arr2)
print(arr2[0,0])
print(arr2[0, 1])
print(arr2[1, 1])

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
10
2
5


ㅤ

ㅤ

### **2) 슬라이싱(Slicing)**

: 를 이용하여 연속 데이터를 추출합니다.



1.   : 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주합니다.
2.   : 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주합니다.
3.   : 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주합니다.



In [ ]:
arr = np.arange(1,10)
print(arr)
print(arr[0:2])
print(arr[0:])
print(arr[3:])

[1 2 3 4 5 6 7 8 9]
[1 2]
[1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]


ㅤ

2차원 ndarray에서 슬라이싱으로 데이터에 접근할 때는 콤마(,)로 행과 열 인덱스를 지칭합니다.

In [ ]:
arr1 = arr.reshape(3,3)
print(arr1)
print("-------")
print(arr1[0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------
[[1 2 3]
 [4 5 6]]


ㅤ

2차원 배열안에 있는 1차원 배열들 중에서 0번째와 1번째 배열을 가져옵니다.

ㅤ

2차원 배열안에 있는 1차원 배열들 중에서 0번째부터 2번째까지 가져오고 가져온 1차원 배열 안에서 1번째부터 2번째까지 가져옵니다.

ㅤ

2차원 배열안에 있는 1차원 배열들 중에서 1번째부터 맨 마지막번째까지 가져오고 가져온 1차원 배열안에서 맨 처음부터 1번째까지 가져옵니다.

ㅤ

2차원 배열안에 있는 1차원 배열들 중에서 0번째부터 2번째까지 가져오고 가져온 1차원 배열안에서 0번째까지 가져옵니다.

ㅤ

### **3) 팬시 인덱싱**





리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환합니다.

In [ ]:
print(array1)
print('-'*10)

print(array1[[0,2]]) #0 행과 2행
print('-'*10)

print(array1[[0,2], 1]) #0행과 2행 중 1열
print('-'*10)

print(array1[[0,2], 0:2]) #0행과 2행의 0~1열

ㅤ

### **4) 불린 인덱싱**

조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용됩니다.

* 1차원 불리언 배열 인덱싱
--  [ ]대괄호안에 숫자나, 범위를 넣어주는것이 아니라 Boolean을 넣어줌
-- Boolean은 True(1) , False(0)으로 만 이루어져있는 자료형
-- 불리언 인덱싱을 사용할때 주의할점은 불리언배열과 인덱싱할배열이 같은 크기여야

ㅤ

In [ ]:
a = [1,2]
b = [1,2]

print(a==b)
print(a is b)
print(id(a), id(b))

True
False
138175362746368 138175363118784


In [ ]:
arr = np.array([0,1,2,3,4,5])
arr2 = np.array([False, True, False, True, False, True])
arr[arr2]

array([1, 3, 5])

In [ ]:
boolean  = arr[arr > 3]
print(boolean)

[4 5]


In [ ]:
boolean = arr[ (arr> 3) & (arr%2 ==0)]
print(boolean)

[4]


## **5. 행렬의 정렬  - sort()와 argsort()**

### **1) 행렬 정렬**



*   np.sort() : 원본 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환합니다.
*   ndarray.sort() : 원본 행렬 자체를 정렬합니다. 반환 값은 None 입니다.



In [ ]:
org_arr = np.array([4,2,8,6])
print(org_arr)
print(np.sort(org_arr)) #원본 값이 변경 되지 않음.
print(org_arr)
print(org_arr.sort()) #반환 값 없음
print(org_arr) #원본 자체를 정렬, 값을 바꿈

[4 2 8 6]
[2 4 6 8]
[4 2 8 6]
None
[2 4 6 8]


ㅤ

내림차순으로 반환하기 위해서는 np.sort에서 다음과 같이 [::-1]을 붙여줍니다.

In [ ]:
print(np.sort(org_arr)[::-1])

[8 6 4 2]


ㅤ

2차원 배열은 axis 축 값 설정을 통해 행열 정렬을 수행합니다.

*   axis = 0 : 행 방향
*   axis = 1 : 열 방향
* 오름차순 :
-- 2차원배열 행기준 : np.sort(배열, axis=0)
-- 2차원배열 열기준 : np.sort(배열, axis=1)
* 내림차순 :
-- 행기준 : np.sort(배열, axis=0)[::-1]
-- 열기준 : np.sort(배열, axis=1)[::-1]




In [ ]:
array2 = np.array([[8, 1], [7, 12]])

print(array2)

print('열 방향 정렬:\n', np.sort(array2, axis = 1))
print('행 방향 정렬:\n', np.sort(array2, axis = 0))

ㅤ

### **2) np.argsort() : 정렬된 행렬의 인덱스를 반환하기**

argsort()는 넘파이에서 매우 활용도가 높습니다.

In [ ]:
print(np.argsort(org_arr))

[0 1 2 3]


ㅤ

np.argsort 역시 np.sort와 마찬가지로 내림차순 반환이 가능합니다.

In [ ]:
print(np.argsort(org_arr)[::-1])

[3 2 1 0]


ㅤ

## **7. 배열 간 사칙연산**

동일한 모양의 두 배열을 사칙연산합니다.(배열 두개만 가능)
* 두 배열 더하기 : np.add(배열1, 배열2)
* 두 배열 빼기 : np.subtract(배열1, 배열2)
* 두 배열 곱하기 : np.multiply(배열1, 배열2)
* 두 배열 나누기 : np.divide(배열1, 배열2)

In [ ]:
arr = np.array([[11,12,13], [2,3,4]])
print(arr)
print("*"*10)
print(arr+arr)

[[11 12 13]
 [ 2  3  4]]
**********
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a = np.array([1,2,3])
b = np.array([3,2,1])
sum = np.add(a,b)
print(sum)
sub = np.subtract(a,b)
print(sub)
multi = np.multiply(a,b)
print(multi)
div = np.divide(a,b)
print(div)

[4 4 4]
[-2  0  2]
[3 4 3]
[0.33333333 1.         3.        ]


배열 내 같은 위치의 원소끼리 연산을 합니다.

* == 사용해서 같은 값인지 비교

In [ ]:
a == b

array([False,  True, False])

배열 비교해 최대값과 최소값을 찾기  ※ 배열두개만 가능
* 두 배열중 최대값 : np.maximum(배열1, 배열2)
* 두 배열중 최소값 : np.minimum(배열1, 배열2)

In [ ]:
print(np.maximum(a,b))
print(np.minimum(a,b))

[3 2 3]
[1 2 1]


ㅤ

## **8. Broadcasting**

배열과 1개의 숫자를 사칙 연산합니다.

In [ ]:
print(a)
print(a+13)
print(a*13)

[1 2 3]
[14 15 16]
[13 26 39]


ㅤ

같은 수의 행과 열을 가진 여러 개의 배열을 연산할 수도 있습니다.

In [ ]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array([[1,2,3],[4,5,6],[1,2,3]])
print(a1)
print("*"*10)
print(a2)
print("*"*10)
print(a1+a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**********
[[1 2 3]
 [4 5 6]
 [1 2 3]]
**********
[[ 2  4  6]
 [ 8 10 12]
 [ 8 10 12]]


ㅤ

다른 형태의 배열끼리도 연산이 가능합니다.

ㅤ

## **9. 집계(Aggregation)**

### **1) 합계**

배열의 합계는 .sum() 을 이용합니다.

In [ ]:
a = np.array([1,2,3,4,5])

print(a.sum())

15


누적합계는 .cumsum() 이용

In [ ]:
print(a.cumsum())

[ 1  3  6 10 15]


ㅤ

축을 설정하여 열 방향 혹은 행 방향으로만 더할 수 있습니다.

In [ ]:
print(a.sum(axis = 0))
#print(a.sum(axis =1))

15


ㅤ

### **2) 평균**

배열의 평균은 .mean()을 이용합니다.

ㅤ

In [ ]:
print(a.mean())

3.0


### **3) 곱셈**

배열의 곱샘은 .prod()을 이용합니다.

In [ ]:
print(a.prod())

120


누적 곱셉은 .cumprod()

In [ ]:
print(a.cumprod())

[  1   2   6  24 120]


ㅤ

### **4) 최댓값과 최솟값**

최댓값과 최솟값은 각각 .max()와 .min()을 이용합니다.

In [ ]:
print(a.max())
print(a.min())

5
1


ㅤ

인덱싱으로 해당 열의 최댓값과 최솟값을 구할 수도 있습니다.

In [ ]:
print(a)
print(a[1].max())
print(a[0].min())

ㅤ

.argmax()와 .argmin()을 이용하여 배열에서 최댓값인 원소의 인덱스 번호와 최솟값인 원소의 인덱스 번호를 구할 수 있습니다.

In [ ]:
print(a.argmax())
print(a.argmin())

ㅤ

### **5) 표준편차와 분산**

표준편차와 분산은 각각 .std()와 .var()을 이용합니다.
* 분산 : 값들이 퍼져있는 정도 내가 만든범위(배열)에서 값들이 얼마나 퍼져있는지.
* 예를들면 1,2,3의 분산과 100,101,102의 분산은 같음.
* 수의 절대적인 크기가 아닌 내가 정한 범위안에서 이값들이 퍼져있는 정도
* 표준편차 : 분산의 수치가 커서 제곱근으로 적당하게 줄인 값

In [ ]:
print(a.std())
print(a.var())

1.4142135623730951
2.0


### **6) 중복제거**
 .unique()



---




In [ ]:
a = np.array([1,2,1,2,3,4,5,6,6,10,10])

print(np.unique(a))

[ 1  2  3  4  5  6 10]


배열간 연산과 인덱싱, 슬라이싱은 Pandas와 함께 데이터 병합과 전처리를 진행할 때 유용하게 쓰이는 방법